// Generated by gencpp from file relaxed_ik/IKSolution.msg
// DO NOT EDIT!


#ifndef RELAXED_IK_MESSAGE_IKSOLUTION_H
#define RELAXED_IK_MESSAGE_IKSOLUTION_H

#include <ros/service_traits.h>


#include <relaxed_ik/IKSolutionRequest.h>
#include <relaxed_ik/IKSolutionResponse.h>


namespace relaxed_ik
{

struct IKSolution
{

typedef IKSolutionRequest Request;
typedef IKSolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IKSolution
} // namespace relaxed_ik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::relaxed_ik::IKSolution > {
  static const char* value()
  {
    return "e880646518d0e045f0fd574a26c68ad6";
  }

  static const char* value(const ::relaxed_ik::IKSolution&) { return value(); }
};

template<>
struct DataType< ::relaxed_ik::IKSolution > {
  static const char* value()
  {
    return "relaxed_ik/IKSolution";
  }

  static const char* value(const ::relaxed_ik::IKSolution&) { return value(); }
};


// service_traits::MD5Sum< ::relaxed_ik::IKSolutionRequest> should match
// service_traits::MD5Sum< ::relaxed_ik::IKSolution >
template<>
struct MD5Sum< ::relaxed_ik::IKSolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::relaxed_ik::IKSolution >::value();
  }
  static const char* value(const ::relaxed_ik::IKSolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::relaxed_ik::IKSolutionRequest> should match
// service_traits::DataType< ::relaxed_ik::IKSolution >
template<>
struct DataType< ::relaxed_ik::IKSolutionRequest>
{
  static const char* value()
  {
    return DataType< ::relaxed_ik::IKSolution >::value();
  }
  static const char* value(const ::relaxed_ik::IKSolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::relaxed_ik::IKSolutionResponse> should match
// service_traits::MD5Sum< ::relaxed_ik::IKSolution >
template<>
struct MD5Sum< ::relaxed_ik::IKSolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::relaxed_ik::IKSolution >::value();
  }
  static const char* value(const ::relaxed_ik::IKSolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::relaxed_ik::IKSolutionResponse> should match
// service_traits::DataType< ::relaxed_ik::IKSolution >
template<>
struct DataType< ::relaxed_ik::IKSolutionResponse>
{
  static const char* value()
  {
    return DataType< ::relaxed_ik::IKSolution >::value();
  }
  static const char* value(const ::relaxed_ik::IKSolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RELAXED_IK_MESSAGE_IKSOLUTION_H
