// Generated by gencpp from file relaxed_ik/RelaxedIKSolution.msg
// DO NOT EDIT!


#ifndef RELAXED_IK_MESSAGE_RELAXEDIKSOLUTION_H
#define RELAXED_IK_MESSAGE_RELAXEDIKSOLUTION_H

#include <ros/service_traits.h>


#include <relaxed_ik/RelaxedIKSolutionRequest.h>
#include <relaxed_ik/RelaxedIKSolutionResponse.h>


namespace relaxed_ik
{

struct RelaxedIKSolution
{

typedef RelaxedIKSolutionRequest Request;
typedef RelaxedIKSolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelaxedIKSolution
} // namespace relaxed_ik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::relaxed_ik::RelaxedIKSolution > {
  static const char* value()
  {
    return "29b15d468a6abde038d54ab02f005ff8";
  }

  static const char* value(const ::relaxed_ik::RelaxedIKSolution&) { return value(); }
};

template<>
struct DataType< ::relaxed_ik::RelaxedIKSolution > {
  static const char* value()
  {
    return "relaxed_ik/RelaxedIKSolution";
  }

  static const char* value(const ::relaxed_ik::RelaxedIKSolution&) { return value(); }
};


// service_traits::MD5Sum< ::relaxed_ik::RelaxedIKSolutionRequest> should match
// service_traits::MD5Sum< ::relaxed_ik::RelaxedIKSolution >
template<>
struct MD5Sum< ::relaxed_ik::RelaxedIKSolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::relaxed_ik::RelaxedIKSolution >::value();
  }
  static const char* value(const ::relaxed_ik::RelaxedIKSolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::relaxed_ik::RelaxedIKSolutionRequest> should match
// service_traits::DataType< ::relaxed_ik::RelaxedIKSolution >
template<>
struct DataType< ::relaxed_ik::RelaxedIKSolutionRequest>
{
  static const char* value()
  {
    return DataType< ::relaxed_ik::RelaxedIKSolution >::value();
  }
  static const char* value(const ::relaxed_ik::RelaxedIKSolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::relaxed_ik::RelaxedIKSolutionResponse> should match
// service_traits::MD5Sum< ::relaxed_ik::RelaxedIKSolution >
template<>
struct MD5Sum< ::relaxed_ik::RelaxedIKSolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::relaxed_ik::RelaxedIKSolution >::value();
  }
  static const char* value(const ::relaxed_ik::RelaxedIKSolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::relaxed_ik::RelaxedIKSolutionResponse> should match
// service_traits::DataType< ::relaxed_ik::RelaxedIKSolution >
template<>
struct DataType< ::relaxed_ik::RelaxedIKSolutionResponse>
{
  static const char* value()
  {
    return DataType< ::relaxed_ik::RelaxedIKSolution >::value();
  }
  static const char* value(const ::relaxed_ik::RelaxedIKSolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RELAXED_IK_MESSAGE_RELAXEDIKSOLUTION_H
