// Generated by gencpp from file relaxed_ik/SelfCollisionQuery.msg
// DO NOT EDIT!


#ifndef RELAXED_IK_MESSAGE_SELFCOLLISIONQUERY_H
#define RELAXED_IK_MESSAGE_SELFCOLLISIONQUERY_H

#include <ros/service_traits.h>


#include <relaxed_ik/SelfCollisionQueryRequest.h>
#include <relaxed_ik/SelfCollisionQueryResponse.h>


namespace relaxed_ik
{

struct SelfCollisionQuery
{

typedef SelfCollisionQueryRequest Request;
typedef SelfCollisionQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SelfCollisionQuery
} // namespace relaxed_ik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::relaxed_ik::SelfCollisionQuery > {
  static const char* value()
  {
    return "d289451142e9cb058f505f73f3b1fafc";
  }

  static const char* value(const ::relaxed_ik::SelfCollisionQuery&) { return value(); }
};

template<>
struct DataType< ::relaxed_ik::SelfCollisionQuery > {
  static const char* value()
  {
    return "relaxed_ik/SelfCollisionQuery";
  }

  static const char* value(const ::relaxed_ik::SelfCollisionQuery&) { return value(); }
};


// service_traits::MD5Sum< ::relaxed_ik::SelfCollisionQueryRequest> should match
// service_traits::MD5Sum< ::relaxed_ik::SelfCollisionQuery >
template<>
struct MD5Sum< ::relaxed_ik::SelfCollisionQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::relaxed_ik::SelfCollisionQuery >::value();
  }
  static const char* value(const ::relaxed_ik::SelfCollisionQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::relaxed_ik::SelfCollisionQueryRequest> should match
// service_traits::DataType< ::relaxed_ik::SelfCollisionQuery >
template<>
struct DataType< ::relaxed_ik::SelfCollisionQueryRequest>
{
  static const char* value()
  {
    return DataType< ::relaxed_ik::SelfCollisionQuery >::value();
  }
  static const char* value(const ::relaxed_ik::SelfCollisionQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::relaxed_ik::SelfCollisionQueryResponse> should match
// service_traits::MD5Sum< ::relaxed_ik::SelfCollisionQuery >
template<>
struct MD5Sum< ::relaxed_ik::SelfCollisionQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::relaxed_ik::SelfCollisionQuery >::value();
  }
  static const char* value(const ::relaxed_ik::SelfCollisionQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::relaxed_ik::SelfCollisionQueryResponse> should match
// service_traits::DataType< ::relaxed_ik::SelfCollisionQuery >
template<>
struct DataType< ::relaxed_ik::SelfCollisionQueryResponse>
{
  static const char* value()
  {
    return DataType< ::relaxed_ik::SelfCollisionQuery >::value();
  }
  static const char* value(const ::relaxed_ik::SelfCollisionQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RELAXED_IK_MESSAGE_SELFCOLLISIONQUERY_H
