# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rain_unity/Human_orion.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import rain_unity.msg
import std_msgs.msg

class Human_orion(genpy.Message):
  _md5sum = "68d6ddc9f4bdf28d17d047e58c8d08d8"
  _type = "rain_unity/Human_orion"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

# A unique ID for this Frame.
int32 lmc_frame_id

# How many hands were detected in the frame
int32 nr_of_hands

# How many fingers were detected in the frame
int32 nr_of_fingers

# How many gestures were detected in the frame
int32 nr_of_gestures

# The rate at which the Leap Motion software is providing frames of data (in frames per second). 
float32 current_frames_per_second

# A string containing a brief, human readable description of the Frame object. 
string to_string

# If there were any hands detected in the frame then the 
# hand.msg will be added here
Hand_orion right_hand
Hand_orion left_hand


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: rain_unity/Hand_orion
std_msgs/Header header

# A unique ID assigned to this Hand object
int32 lmc_hand_id

# This changed to between true/false depending if there's a hand detected in the LMC frame
bool is_present

# This changed to between true/false depending if there's a hand detected in the LMC frame
bool valid_gestures

# The duration of time this Hand has been visible to the Leap Motion Controller. 
float32 time_visible

# How confident we are with a given hand pose. 
# The confidence level ranges between 0.0 and 1.0 inclusive.
float32 confidence

# The following three angles are in radians!
float32 roll
float32 pitch
float32 yaw

# The angle between the fingers and the hand of a grab hand pose. 
# In radians
float32 grab_strength

# The distance between the thumb and index finger of a pinch hand pose. 
float32 pinch_strength

# The rate of change of the palm position in meters/second. 
float32[] palm_velocity

# The center position of the palm in millimeters from the Leap Motion Controller origin. 
geometry_msgs/Point palm_center

# The estimated width of the palm when the hand is in a flat position. 
float32 palm_width

# The radius (m) of a sphere fit to the curvature of this hand. 
float32 sphere_radius

# The center of a sphere fit to the curvature of this hand. 
float32[] sphere_center

# The position of the wrist of this hand. 
float32[] wrist_position

# A string containing a brief, human readable description of the Hand object. 
string to_string 

# (Newly added from "Hand.msg") 
# The normal vector of the palm (w.r.t. the coordination of the global frame in VR). 
geometry_msgs/Vector3 palm_normal 

# The direction vector of the palm (w.r.t. the coordination of the global frame in VR). 
geometry_msgs/Vector3 palm_direction 


# A list of fingers and gestures assosciated with this hand (Commented for RAIN demonstration)
# Finger[] finger_list
# Gesture[] gesture_list
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','lmc_frame_id','nr_of_hands','nr_of_fingers','nr_of_gestures','current_frames_per_second','to_string','right_hand','left_hand']
  _slot_types = ['std_msgs/Header','int32','int32','int32','int32','float32','string','rain_unity/Hand_orion','rain_unity/Hand_orion']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lmc_frame_id,nr_of_hands,nr_of_fingers,nr_of_gestures,current_frames_per_second,to_string,right_hand,left_hand

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Human_orion, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lmc_frame_id is None:
        self.lmc_frame_id = 0
      if self.nr_of_hands is None:
        self.nr_of_hands = 0
      if self.nr_of_fingers is None:
        self.nr_of_fingers = 0
      if self.nr_of_gestures is None:
        self.nr_of_gestures = 0
      if self.current_frames_per_second is None:
        self.current_frames_per_second = 0.
      if self.to_string is None:
        self.to_string = ''
      if self.right_hand is None:
        self.right_hand = rain_unity.msg.Hand_orion()
      if self.left_hand is None:
        self.left_hand = rain_unity.msg.Hand_orion()
    else:
      self.header = std_msgs.msg.Header()
      self.lmc_frame_id = 0
      self.nr_of_hands = 0
      self.nr_of_fingers = 0
      self.nr_of_gestures = 0
      self.current_frames_per_second = 0.
      self.to_string = ''
      self.right_hand = rain_unity.msg.Hand_orion()
      self.left_hand = rain_unity.msg.Hand_orion()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4if().pack(_x.lmc_frame_id, _x.nr_of_hands, _x.nr_of_fingers, _x.nr_of_gestures, _x.current_frames_per_second))
      _x = self.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.right_hand.header.seq, _x.right_hand.header.stamp.secs, _x.right_hand.header.stamp.nsecs))
      _x = self.right_hand.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i2B7f().pack(_x.right_hand.lmc_hand_id, _x.right_hand.is_present, _x.right_hand.valid_gestures, _x.right_hand.time_visible, _x.right_hand.confidence, _x.right_hand.roll, _x.right_hand.pitch, _x.right_hand.yaw, _x.right_hand.grab_strength, _x.right_hand.pinch_strength))
      length = len(self.right_hand.palm_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.right_hand.palm_velocity))
      _x = self
      buff.write(_get_struct_3d2f().pack(_x.right_hand.palm_center.x, _x.right_hand.palm_center.y, _x.right_hand.palm_center.z, _x.right_hand.palm_width, _x.right_hand.sphere_radius))
      length = len(self.right_hand.sphere_center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.right_hand.sphere_center))
      length = len(self.right_hand.wrist_position)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.right_hand.wrist_position))
      _x = self.right_hand.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6d3I().pack(_x.right_hand.palm_normal.x, _x.right_hand.palm_normal.y, _x.right_hand.palm_normal.z, _x.right_hand.palm_direction.x, _x.right_hand.palm_direction.y, _x.right_hand.palm_direction.z, _x.left_hand.header.seq, _x.left_hand.header.stamp.secs, _x.left_hand.header.stamp.nsecs))
      _x = self.left_hand.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i2B7f().pack(_x.left_hand.lmc_hand_id, _x.left_hand.is_present, _x.left_hand.valid_gestures, _x.left_hand.time_visible, _x.left_hand.confidence, _x.left_hand.roll, _x.left_hand.pitch, _x.left_hand.yaw, _x.left_hand.grab_strength, _x.left_hand.pinch_strength))
      length = len(self.left_hand.palm_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.left_hand.palm_velocity))
      _x = self
      buff.write(_get_struct_3d2f().pack(_x.left_hand.palm_center.x, _x.left_hand.palm_center.y, _x.left_hand.palm_center.z, _x.left_hand.palm_width, _x.left_hand.sphere_radius))
      length = len(self.left_hand.sphere_center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.left_hand.sphere_center))
      length = len(self.left_hand.wrist_position)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.left_hand.wrist_position))
      _x = self.left_hand.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.left_hand.palm_normal.x, _x.left_hand.palm_normal.y, _x.left_hand.palm_normal.z, _x.left_hand.palm_direction.x, _x.left_hand.palm_direction.y, _x.left_hand.palm_direction.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.right_hand is None:
        self.right_hand = rain_unity.msg.Hand_orion()
      if self.left_hand is None:
        self.left_hand = rain_unity.msg.Hand_orion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.lmc_frame_id, _x.nr_of_hands, _x.nr_of_fingers, _x.nr_of_gestures, _x.current_frames_per_second,) = _get_struct_4if().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.to_string = str[start:end].decode('utf-8')
      else:
        self.to_string = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.right_hand.header.seq, _x.right_hand.header.stamp.secs, _x.right_hand.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.right_hand.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.right_hand.lmc_hand_id, _x.right_hand.is_present, _x.right_hand.valid_gestures, _x.right_hand.time_visible, _x.right_hand.confidence, _x.right_hand.roll, _x.right_hand.pitch, _x.right_hand.yaw, _x.right_hand.grab_strength, _x.right_hand.pinch_strength,) = _get_struct_i2B7f().unpack(str[start:end])
      self.right_hand.is_present = bool(self.right_hand.is_present)
      self.right_hand.valid_gestures = bool(self.right_hand.valid_gestures)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.palm_velocity = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 32
      (_x.right_hand.palm_center.x, _x.right_hand.palm_center.y, _x.right_hand.palm_center.z, _x.right_hand.palm_width, _x.right_hand.sphere_radius,) = _get_struct_3d2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.sphere_center = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.wrist_position = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.to_string = str[start:end].decode('utf-8')
      else:
        self.right_hand.to_string = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.right_hand.palm_normal.x, _x.right_hand.palm_normal.y, _x.right_hand.palm_normal.z, _x.right_hand.palm_direction.x, _x.right_hand.palm_direction.y, _x.right_hand.palm_direction.z, _x.left_hand.header.seq, _x.left_hand.header.stamp.secs, _x.left_hand.header.stamp.nsecs,) = _get_struct_6d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.left_hand.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.left_hand.lmc_hand_id, _x.left_hand.is_present, _x.left_hand.valid_gestures, _x.left_hand.time_visible, _x.left_hand.confidence, _x.left_hand.roll, _x.left_hand.pitch, _x.left_hand.yaw, _x.left_hand.grab_strength, _x.left_hand.pinch_strength,) = _get_struct_i2B7f().unpack(str[start:end])
      self.left_hand.is_present = bool(self.left_hand.is_present)
      self.left_hand.valid_gestures = bool(self.left_hand.valid_gestures)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.palm_velocity = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 32
      (_x.left_hand.palm_center.x, _x.left_hand.palm_center.y, _x.left_hand.palm_center.z, _x.left_hand.palm_width, _x.left_hand.sphere_radius,) = _get_struct_3d2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.sphere_center = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.wrist_position = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.to_string = str[start:end].decode('utf-8')
      else:
        self.left_hand.to_string = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.left_hand.palm_normal.x, _x.left_hand.palm_normal.y, _x.left_hand.palm_normal.z, _x.left_hand.palm_direction.x, _x.left_hand.palm_direction.y, _x.left_hand.palm_direction.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4if().pack(_x.lmc_frame_id, _x.nr_of_hands, _x.nr_of_fingers, _x.nr_of_gestures, _x.current_frames_per_second))
      _x = self.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.right_hand.header.seq, _x.right_hand.header.stamp.secs, _x.right_hand.header.stamp.nsecs))
      _x = self.right_hand.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i2B7f().pack(_x.right_hand.lmc_hand_id, _x.right_hand.is_present, _x.right_hand.valid_gestures, _x.right_hand.time_visible, _x.right_hand.confidence, _x.right_hand.roll, _x.right_hand.pitch, _x.right_hand.yaw, _x.right_hand.grab_strength, _x.right_hand.pinch_strength))
      length = len(self.right_hand.palm_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.right_hand.palm_velocity.tostring())
      _x = self
      buff.write(_get_struct_3d2f().pack(_x.right_hand.palm_center.x, _x.right_hand.palm_center.y, _x.right_hand.palm_center.z, _x.right_hand.palm_width, _x.right_hand.sphere_radius))
      length = len(self.right_hand.sphere_center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.right_hand.sphere_center.tostring())
      length = len(self.right_hand.wrist_position)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.right_hand.wrist_position.tostring())
      _x = self.right_hand.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6d3I().pack(_x.right_hand.palm_normal.x, _x.right_hand.palm_normal.y, _x.right_hand.palm_normal.z, _x.right_hand.palm_direction.x, _x.right_hand.palm_direction.y, _x.right_hand.palm_direction.z, _x.left_hand.header.seq, _x.left_hand.header.stamp.secs, _x.left_hand.header.stamp.nsecs))
      _x = self.left_hand.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_i2B7f().pack(_x.left_hand.lmc_hand_id, _x.left_hand.is_present, _x.left_hand.valid_gestures, _x.left_hand.time_visible, _x.left_hand.confidence, _x.left_hand.roll, _x.left_hand.pitch, _x.left_hand.yaw, _x.left_hand.grab_strength, _x.left_hand.pinch_strength))
      length = len(self.left_hand.palm_velocity)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.left_hand.palm_velocity.tostring())
      _x = self
      buff.write(_get_struct_3d2f().pack(_x.left_hand.palm_center.x, _x.left_hand.palm_center.y, _x.left_hand.palm_center.z, _x.left_hand.palm_width, _x.left_hand.sphere_radius))
      length = len(self.left_hand.sphere_center)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.left_hand.sphere_center.tostring())
      length = len(self.left_hand.wrist_position)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.left_hand.wrist_position.tostring())
      _x = self.left_hand.to_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.left_hand.palm_normal.x, _x.left_hand.palm_normal.y, _x.left_hand.palm_normal.z, _x.left_hand.palm_direction.x, _x.left_hand.palm_direction.y, _x.left_hand.palm_direction.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.right_hand is None:
        self.right_hand = rain_unity.msg.Hand_orion()
      if self.left_hand is None:
        self.left_hand = rain_unity.msg.Hand_orion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.lmc_frame_id, _x.nr_of_hands, _x.nr_of_fingers, _x.nr_of_gestures, _x.current_frames_per_second,) = _get_struct_4if().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.to_string = str[start:end].decode('utf-8')
      else:
        self.to_string = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.right_hand.header.seq, _x.right_hand.header.stamp.secs, _x.right_hand.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.right_hand.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.right_hand.lmc_hand_id, _x.right_hand.is_present, _x.right_hand.valid_gestures, _x.right_hand.time_visible, _x.right_hand.confidence, _x.right_hand.roll, _x.right_hand.pitch, _x.right_hand.yaw, _x.right_hand.grab_strength, _x.right_hand.pinch_strength,) = _get_struct_i2B7f().unpack(str[start:end])
      self.right_hand.is_present = bool(self.right_hand.is_present)
      self.right_hand.valid_gestures = bool(self.right_hand.valid_gestures)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.palm_velocity = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 32
      (_x.right_hand.palm_center.x, _x.right_hand.palm_center.y, _x.right_hand.palm_center.z, _x.right_hand.palm_width, _x.right_hand.sphere_radius,) = _get_struct_3d2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.sphere_center = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.right_hand.wrist_position = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.right_hand.to_string = str[start:end].decode('utf-8')
      else:
        self.right_hand.to_string = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.right_hand.palm_normal.x, _x.right_hand.palm_normal.y, _x.right_hand.palm_normal.z, _x.right_hand.palm_direction.x, _x.right_hand.palm_direction.y, _x.right_hand.palm_direction.z, _x.left_hand.header.seq, _x.left_hand.header.stamp.secs, _x.left_hand.header.stamp.nsecs,) = _get_struct_6d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.left_hand.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.left_hand.lmc_hand_id, _x.left_hand.is_present, _x.left_hand.valid_gestures, _x.left_hand.time_visible, _x.left_hand.confidence, _x.left_hand.roll, _x.left_hand.pitch, _x.left_hand.yaw, _x.left_hand.grab_strength, _x.left_hand.pinch_strength,) = _get_struct_i2B7f().unpack(str[start:end])
      self.left_hand.is_present = bool(self.left_hand.is_present)
      self.left_hand.valid_gestures = bool(self.left_hand.valid_gestures)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.palm_velocity = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 32
      (_x.left_hand.palm_center.x, _x.left_hand.palm_center.y, _x.left_hand.palm_center.z, _x.left_hand.palm_width, _x.left_hand.sphere_radius,) = _get_struct_3d2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.sphere_center = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.left_hand.wrist_position = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.left_hand.to_string = str[start:end].decode('utf-8')
      else:
        self.left_hand.to_string = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.left_hand.palm_normal.x, _x.left_hand.palm_normal.y, _x.left_hand.palm_normal.z, _x.left_hand.palm_direction.x, _x.left_hand.palm_direction.y, _x.left_hand.palm_direction.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d2f = None
def _get_struct_3d2f():
    global _struct_3d2f
    if _struct_3d2f is None:
        _struct_3d2f = struct.Struct("<3d2f")
    return _struct_3d2f
_struct_4if = None
def _get_struct_4if():
    global _struct_4if
    if _struct_4if is None:
        _struct_4if = struct.Struct("<4if")
    return _struct_4if
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_6d3I = None
def _get_struct_6d3I():
    global _struct_6d3I
    if _struct_6d3I is None:
        _struct_6d3I = struct.Struct("<6d3I")
    return _struct_6d3I
_struct_i2B7f = None
def _get_struct_i2B7f():
    global _struct_i2B7f
    if _struct_i2B7f is None:
        _struct_i2B7f = struct.Struct("<i2B7f")
    return _struct_i2B7f
